# Generated by Django 5.1.5 on 2025-02-02 01:09

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('0', 'Please select'), ('1', 'Physics')], default='0', max_length=32),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to=student.models.student_directory_name),
        ),
    ]
