# Generated by Django 5.1.5 on 2025-02-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_course_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('Please select', '0'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics'), ('English', 'English'), ('Bangla', 'Bangla'), ('Computer Science', 'CSE')], default='Please select', max_length=32),
        ),
    ]
