# Generated by Django 5.1.5 on 2025-02-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('', 'Please select'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics'), ('English', 'English'), ('Bangla', 'Bangla'), ('Computer Science', 'CSE')], default='', max_length=32),
        ),
    ]
